image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

docker build -t registry.gitlab.com/laurent.malvert/software-factory .
docker push registry.gitlab.com/laurent.malvert/software-factory

build-master:
  stage: build
  script:
    - docker-compose build --pull --force-rm --no-cache
    - docker-compose push
  only:
    - master

build:
  stage: build
  script:
    - docker-compose build --pull --force-rm --no-cache ":$CI_COMMIT_REF_SLUG" .
    - docker-compose push ":$CI_COMMIT_REF_SLUG"
  except:
    - master
