###########################################################################
# Software Factory
###########################################################################
#  These services are the building blocks for a software factory
# environment, composed of:
#   - jenkins for Continuous Integration and Continuous Delivery (CI/CD),
#   - sonarqube for Continuous Inspection,
#   - nexus for Artifact/archive Repository Management.
###########################################################################

version: "3"

services:

  # Use an nginx reverse-proxy to expose all our public web services on
  # the same host, via standard ports by using virtual hosts.
  # See: https://github.com/jwilder/nginx-proxy
  #
  # Virtual hosts are defined by an environment variable in each service's
  # <service>.env file as:
  #   VIRTUAL_HOST=<service>.<hostname>
  # The main host name is defined in the proxy's proxy.env file
  proxy:
    image: jwilder/nginx-proxy
    depends_on:
      - jenkins
      - nexus
      - sonarqube
      - mailhog
    env_file:
      - proxy/proxy.env
    ports:
      - "80:80"
    networks:
      - softwarefactorynet
      - jenkinsnet
      - nexusnet
      - sonarnet
      - mailhognet
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro

  jenkins:
    image: jenkins/jenkins:lts
    env_file:
      - jenkins/jenkins-server/jenkins.env
    expose:
      - "8080"  # default web server listening port
      - "50000" # default JNLP slave listening port
    networks:
      - softwarefactorynet
      - jenkinsnet
      - nexusnet
      - mailhognet
    extra_hosts:
      - "nexus.software-factory.lan:172.20.0.1"
      - "sonarqube.software-factory.lan:172.20.0.1"
      - "mailhog.software-factory.lan:172.20.0.1"
    volumes:
      # so that jenkins-in-docker can start containers
      # on its host's docker engine rather than doing
      # Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # WARNING: Because of slow host mounts performance (especially
      # in docker for mac), you may want to configure your Jenkins instance
      # to not store some folders inside jenkins_home
      # (e.g. fingersprints, jobs, workspace...)
      # We use host mounts by default to easily restore a Jenkins
      # configuration (for now) and avoid data loss.
      - jenkins-data:/var/jenkins_home
      - /opt/software-factory/jenkins/data:/var/jenkins_home

  nexus:
    image: sonatype/nexus3:3.9.0
    env_file:
      - nexus/nexus.env
    expose:
      - "8081"
    networks:
      - softwarefactorynet
      - nexusnet
    volumes:
      - nexus-data:/nexus-data
      - /opt/software-factory/nexus/data:/nexus-data

  sonarqube:
    image: sonarqube:lts
    depends_on:
      - sonarqube_database
    env_file:
      - sonarqube/sonarqube.env
    expose:
      - "9000"
    networks:
      - softwarefactorynet
      - sonarnet
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - /opt/software-factory/sonarqube/conf:/opt/sonarqube/conf
      - /opt/software-factory/sonarqube/data:/opt/sonarqube/conf
      - /opt/software-factory/sonarqube/extensions:/opt/sonarqube/extensions

  sonarqube_database:
    image: mysql:5.7
    env_file:
      - sonarqube/sonarqube_database.env
    expose:
      - "3306"
    networks:
      - sonarnet
    volumes:
#      - sonarqube-database:/var/lib/mysql:rw
      - /opt/sonarqube/database:/var/lib/mysql:rw

  # This service is *only* meant to be used to test emailing functionalities,
  # and NOT to deploy a real email server, as we simply use mailhog to send
  # and catch emails.
  mailhog:
    image: mailhog/mailhog
    expose:
      - "1025"
      - "8025"
    networks:
      - softwarefactorynet
      - mailhognet
    env_file:
      - mailhog/mailhog.env


networks:
  softwarefactorynet:
    driver: bridge
  jenkinsnet:
    driver: bridge
  nexusnet:
    driver: bridge
  sonarnet:
    driver: bridge
  mailhognet:
    driver: bridge


volumes:
  jenkins-data:
  nexus-data:
  sonarqube-conf:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-bundled-plugins:
